name:                HaskellCoin
version:             0.1.0.0
github:              "githubuser/HaskellCoin"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HaskellCoin#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.4.0
- basement == 0.0.12
- cryptonite == 0.30
- bytestring == 0.11.3.1
library:
  source-dirs: src

executables:
  HaskellCoin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellCoin
